<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/klass.min.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/code.photoswipe.jquery-3.0.5.js') ?>"></script>
<?php
/**
 * Cloud Image Zoom - Magento Extension
 *
 * @package     CloudZoom
 * @category    EcommerceTeam
 * @copyright   Copyright 2011 EcommerceTeam Inc. (http://www.ecommerce-team.com)
 * @version:    1.1.3
 */

/** @var $this Mage_Catalog_Block_Product_View_Media */
/** @var $product Mage_Catalog_Model_Product */
$product      = $this->getProduct();
/** @var $helper EcommerceTeam_CloudZoom_Helper_Data */
$helper       = Mage::helper('ecommerceteam_cloudzoom');
/** @var $outputHelper Mage_Core_Block_Abstract */
$outputHelper = $this->helper('catalog/output');

$position       = $helper->getConfigData('position');
$showTitle      = intval($helper->getConfigFlag('show_title'));
$titleOpacity   = intval($helper->getConfigData('title_opacity')) / 100;
$lensOpacity    = intval($helper->getConfigData('lens_opacity')) / 100;
$tintColor      = trim($helper->getConfigData('tint_color'));
$tintOpacity    = intval($helper->getConfigData('tint_opacity')) / 100;
$zoomWidth      = intval($helper->getConfigData('zoom_width'));
$zoomHeight     = intval($helper->getConfigData('zoom_height'));
$bigImageWidth  = intval($helper->getConfigData('big_image_width'));
$bigImageHeight = intval($helper->getConfigData('big_image_height'));

$bigImageX  = 400;
$bigImageY = 472;

$config = array(
    "position:'{$position}'",
    "showTitle:{$showTitle}",
    "titleOpacity:{$titleOpacity}",
    "lensOpacity:{$lensOpacity}",
);
    
if ($position == 'inside') {
    $config[] = 'adjustX: -4,adjustY:-4';
} elseif ($position == 'right') {
    $config[] = 'adjustX: 10,adjustY:-4';
} elseif ($position == 'bottom') {
    $config[] = 'adjustX: -4,adjustY:10';
} elseif ($position == 'left') {
    $config[] = 'adjustX: -18,adjustY:-4';
} elseif ($position == 'top') {
    $config[] = 'adjustX: -4,adjustY:-18';
}

if ($tintColor) {
    $config[] = "tint:'{$tintColor}',tintOpacity:{$tintOpacity}";
}

if ($zoomWidth) {
    $config[] = "zoomWidth:{$zoomWidth}";
}

if ($zoomHeight) {
    $config[] = "zoomHeight:{$zoomHeight}";
}
?>

<?php if ($zoomWidth > 50 and $zoomHeight > 50  ): ?>
<style type="text/css">
.cloud-zoom-big {width:<?php echo "$zoomWidth"; ?>px !important; height:<?php echo "$zoomHeight"; ?>px !important;  }
</style>
<?php endif; ?>

<div class="product-box-customs">
    <div class="row">
        <div class="col-md-3">

            <?php if (count($this->getGalleryImages()) > 0): ?>
                <?php if (count($this->getGalleryImages()) > 3)  {
                    $previous = '<a class="fa fa-chevron-circle-up jcarousel-control-prev" href="#"></a>';
                    $next = '<div style="float: left;width: 97px;"><a class="fa fa-chevron-circle-down jcarousel-control-next" href="#"></a></div>';
                } else
                {
                    $previous ='';
                    $next = '';
                } ?>

                <div class="more-views">
                    <h2><?php echo $this->__('More Views') ?></h2>
                    <div style="text-align: center;width: 104px">
                        <div class="jcarousel-wrapper">
                            <?php echo $previous;?>
                            <div class="jcarousel">
                                <ul>
                                    <?php foreach ($this->getGalleryImages() as $_image): ?>
                                        <?php if ($this->isGalleryImageVisible($_image)): ?>
                                            <li>
                                                <a href='<?php echo $this->helper('catalog/image')->init($product, 'image', $_image->getFile())->resize($bigImageWidth, $bigImageHeight);?>' class='cloud-zoom-gallery' title='<?php echo $this->htmlEscape($_image->getLabel()) ?>'
                                                   rel="useZoom: 'zoom1', smallImage: '<?php echo $this->helper('catalog/image')->init($product, 'image', $_image->getFile())->resize($bigImageX, $bigImageY);?>' ">
                                                    <img src="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail', $_image->getFile())->resize(97);?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>"/>
                                                </a>
                                            </li>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                            <?php echo $next;?>
                        </div>
                    </div>

                </div>
                <div class="gallery-swipe-content">
                    <ul id="gallery-swipe" class="gallery-swipe">
                        <?php foreach ($this->getGalleryImages() as $_image): ?>
                            <?php if ($this->isGalleryImageVisible($_image)): ?>
                                <li>
                                    <a href='<?php echo $this->helper('catalog/image')->init($product, 'thumbnail', $_image->getFile())->resize($bigImageWidth, $bigImageHeight);?>'  title='<?php echo $this->htmlEscape($_image->getLabel()) ?>'>
                                        <img src="<?php echo $this->helper('catalog/image')->init($product, 'thumbnail', $_image->getFile())->resize($bigImageWidth, $bigImageHeight);?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>"/>
                                    </a>
                                </li>
                            <?php endif; ?>
                        <?php endforeach; ?>
                    </ul>
                </div>
            <?php endif; ?>
        </div>
        <div class="col-md-9">
            <?php if ($product->getImage() != 'no_selection' && $product->getImage()): ?>

                <p class="product-image">
                    <a  href='<?php echo $this->helper('catalog/image')->init($product, 'image')->resize($bigImageWidth, $bigImageHeight);?>' class = 'cloud-zoom' id='zoom1' rel="<?php echo implode($config, ',');?>">

                        <img class="big" id="image" src="<?php echo $this->helper('catalog/image')->init($product, 'image')->resize($bigImageX, $bigImageY);?>" alt='' title="<?php echo $this->htmlEscape($this->getImageLabel());?>" />
                    </a>
                </p>
            <?php else: ?>
                <p class="product-image">
                    <?php
                    $_img = '<img src="'.$this->helper('catalog/image')->init($product, 'image')->resize($bigImageX, $bigImageY).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
                    echo $outputHelper->productAttribute($product, $_img, 'image');
                    ?>
                </p>

            <?php endif; ?>
        </div>
    </div>


</div>

<?php echo $this->getChildHtml('after'); ?>
<script type="text/javascript">
    (function($) {
        $(function() {
            $('.jcarousel')
                .jcarousel({
                    vertical: true
                });

            $('.jcarousel-control-prev')
                .on('jcarouselcontrol:active', function() {
                    $(this).removeClass('inactive');
                })
                .on('jcarouselcontrol:inactive', function() {
                    $(this).addClass('inactive');
                })
                .jcarouselControl({
                    target: '-=1'
                });

            $('.jcarousel-control-next')
                .on('jcarouselcontrol:active', function() {
                    $(this).removeClass('inactive');
                })
                .on('jcarouselcontrol:inactive', function() {
                    $(this).addClass('inactive');
                })
                .jcarouselControl({
                    target: '+=1'
                });


        });
    })(jQuery);
</script>

